### ISSUE TITLE
[Bug] Hits badge in README.md is not updating

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahl/slides#7]
The badge for number of hits in this repository in README.md is not updating. Seems like a bug in link

**Comment by amanda-ariyaratne** [comment]
Hello, Can I work on this?

**Comment by MadhavBahl** [comment]
Sure, thanks @amanda-ariyaratne

**Comment by MadhavBahl** [comment]
Assigned this issue to you

**Comment by amanda-ariyaratne** [comment]
The link set on README.md is correct. 
Looks like the issue comes from the hits service. Have a look at their open issue [here](https://github.com/dwyl/hits/issues/101).

There is a cloned service of hits by [wesky93](https://github.com/wesky93) called [views](https://github.com/wesky93/views). I tried implementing it and it works fine. Is it okay if I use this to your repo?

**Comment by MadhavBahl** [comment]
@amanda-ariyaratne if it seems genuine and trusted, you can go ahead and create a PR, please test it on your branch once, if it works, we can merge it

**Comment by amanda-ariyaratne** [comment]
I have tested it again, and everything works well. Will create a PR now.
